name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package
        run: mvn --batch-mode --no-transfer-progress package
      - name: Site
        run: mvn --batch-mode --no-transfer-progress site:site
      - name: Stage Site
        run: mvn --batch-mode --no-transfer-progress site:stage
      - name: Publish
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" &&\
          git config --local user.name "github-actions[bot]" &&\
          mvn --settings .settings.xml --batch-mode --no-transfer-progress scm-publish:publish-scm

#        run: mvn --batch-mode site:site site:stage scm-publish:publish-scm
