name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          ssh-known-hosts: 'github.com'
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Package
        run: mvn --batch-mode --no-transfer-progress package
      - name: Site
        run: mvn --batch-mode --no-transfer-progress site:site
      - name: Stage Site
        run: mvn --batch-mode --no-transfer-progress site:stage
      - name: Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mvn --batch-mode --no-transfer-progress site


