name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: ${{ github.repository }}
          token: ${{ secrets.CI }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          server-username: MAVEN_USERNAME # env variable for username in deploy
#          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Package
        run: mvn --batch-mode --no-transfer-progress package
      - name: Site
        run: mvn --batch-mode --no-transfer-progress site:site
      - name: Stage Site
        run: mvn --batch-mode --no-transfer-progress site:stage
      - name: Publish
        run: mvn --batch-mode --no-transfer-progress scm-publish:publish-scm


