name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package
        run: mvn --batch-mode package
      - name: Site
        run: mvn site:site
      - name: Stage Site
        run: mvn site:stage
      - name: Publish
        run: mvn scm-publish:publish-scm

#        run: mvn --batch-mode site:site site:stage scm-publish:publish-scm
